### ISSUE TITLE
openai_api_base support

### ISSUE THREAD

**Issue by C018** [father-bot/chatgpt_telegram_bot#419]
Can openai_api_base support https://xx.com? After customization, it reported an error: Something went wrong during completion. Reason: Invalid response object from API: '404 Not Found' (HTTP response code was 404).

**Comment by MapoMagpie** [comment]
openai_api_base example: `http://example.com/v1`,  the end without '/'

**Comment by neowisard** [comment]
without openai_api_base: http://192.168.0.55:5000/v1
