### ISSUE TITLE
The artist does not yield correct results in different languages.

### ISSUE THREAD

**Issue by MehmetBozkir** [father-bot/chatgpt_telegram_bot#429]
Hello, 
I am a software developer whose native language is Turkish. When I give commands to the painter in my own language, I cannot achieve accurate results.

_Example :_

1. 8 bacaklı kedi çiz (Turkish) = Draw an eight-legged cat (English)
![1](https://github.com/father-bot/chatgpt_telegram_bot/assets/150898451/1e2b31d7-1177-49b0-a8de-d51d07f7b9d9)
![2](https://github.com/father-bot/chatgpt_telegram_bot/assets/150898451/4fb98b57-0d8f-4c97-bf22-b26b62b54064)

The situation is quite evident in these examples. Although it attempted to draw, it made a few mistakes, but as you can see, the results are different. And of course, there's also the issue with the Turkish language support being incorrect.

2. Ahtapot kedi çiz (Turkish) = Draw octopus cat (English)
![3](https://github.com/father-bot/chatgpt_telegram_bot/assets/150898451/2123aaf4-3ce5-420a-b2a6-3751f8db7abd)
![4](https://github.com/father-bot/chatgpt_telegram_bot/assets/150898451/cc112f01-d3e3-48b7-8e21-81cc94ed7a46)

The problem may persist similarly in different languages, so I believe conducting tests on this matter is necessary. 

What can I do to solve this problem??

**Comment by MehmetBozkir** [comment]
I'm waiting for your return bro.

**Comment by keiv-fly** [comment]
I think the problem is that chatgpt is not good at other languages. I heard that in Russian it is better to write the prompt in English and ask for the answer in Russian and the results are better.

In your case I would recommend translating using specialized software like Google translate and then give chatgpt a prompt in English.
