### ISSUE TITLE
vision not working or something else

### ISSUE THREAD

**Issue by kimberk** [father-bot/chatgpt_telegram_bot#446]
<image>

bot, [2.04.2024 22:39]
...

bot, [2.04.2024 22:39]
🥲 You sent empty message. Please, try again!

**Comment by OlegGoless** [comment]
Hi, can you pls share your use case?

**Comment by kimberk** [comment]
<img width="703" alt="Ekran görüntüsü 2024-04-04 081856" src="https://github.com/father-bot/chatgpt_telegram_bot/assets/44027141/4a491b83-7731-419f-9c3d-c6ebbaa451fc">

gpt4-vision

**Comment by OlegGoless** [comment]
Hi, the problem was that we had an empty message check.
now i fix it
