### ISSUE TITLE
Chat context is not preserved, every new message starts a new chat

### ISSUE THREAD

**Issue by ihor-chaban** [father-bot/chatgpt_telegram_bot#451]
As the title says, I noticed this strange behavior after upgrading recently to [57ee703](https://github.com/father-bot/chatgpt_telegram_bot/commit/57ee703f077dae5466c0e59ea5a09fe66f1287e3) (from v1.4 to v1.5)
It looks like the context is not saved and every new message starts a new chat.
I tried the same with different models and modes.

Example:
<img width="1356" alt="Screenshot 2024-04-12 at 7 24 12 PM" src="https://github.com/father-bot/chatgpt_telegram_bot/assets/25959371/0c394c52-6788-403d-9edd-20dc1239b5c9">

No errors were noticed in the logs.

**Comment by zero3366** [comment]
I also encountered this problem, is there any solution?

**Comment by Thetail001** [comment]
+1
![image](https://github.com/father-bot/chatgpt_telegram_bot/assets/56257172/7e9b1cda-5235-4b43-b893-01da95f4853a)

**Comment by OlegGoless** [comment]
hi, i fixed this bug, thank you for your feedback
